version: '3.5'

services:
  frontend:
    container_name: frontend
    build: ./client
    restart: always
    networks:
      - webnet
    volumes:
      - ./client:/client
    env_file:
      - ./.env
    ports:
      - 8080:8080

  backend:
    container_name: backend
    build: ./server
    restart: always
    networks:
      - webnet
    volumes:
      - ./server
    environment:
      - NODE_ENV=production

  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - webnet
    volumes:
      - ./server/public:/public
    env_file:
      - ./.env
    restart: always
    depends_on:
      - backend
#      - frontend
    ports:
      - 80:80


networks:
  webnet:
