version: '2'

services:
  frontend:
    image: 279123992655.dkr.ecr.us-west-2.amazonaws.com/backend_frontend:latest
    build: ./client
    ports:
      - 80:80
    links:
      - backend

  backend:
    image: 279123992655.dkr.ecr.us-west-2.amazonaws.com/backend_backend:latest
    build: ./server
    environment:
      - NODE_ENV=production
